name: Deploy frontend

on:
  push:
    paths:
      - 'web/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'web/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies in the 'web' folder
      working-directory: ./web
      run: |
        npm install

    - name: Build the application
      working-directory: ./web
      run: |
        npm run build

    - name: Upload build artifacts (opcional)
      if: success()
      run: |
        echo "Build successful 🎉"
